blank_issues_enabled: true
contact_links:
  - name: ⁉️ Need help with GraalVM?
    url: https://www.graalvm.org/slack-invitation/
    about: Visit our slack channel.
  - name: Found a security vulnerability??
    url: https://www.oracle.com/corporate/security-practices/assurance/vulnerability/reporting.html
    about: Report a security vulnerability to secalert_us@oracle.com. Click here for additional information.
